### ISSUE TITLE
Could have directly exported the model

### ISSUE THREAD

**Issue by abhaynpai** [prathameshkpai/userapi#1]
`let customers = mongoose.model('customers', Customers);`

`let` is used to declare a constant model.  Ideally you should use `const`. But in this case you need neither. Directly export the model at

https://github.com/prathameshkpai/userapi/blob/4118996e7f6615164b4ce5fd2a7dbb86e0c784a0/models/customer.model.js#L12

**Comment by prathameshkpai** [comment]
okay its done
