### ISSUE TITLE
Error variable and Validations

### ISSUE THREAD

**Issue by abhaynpai** [prathameshkpai/userapi#3]
`ee` is used for the error variable. In this case ideally it should have been something meaningful like `err` or `error`.

Also could you check what happens if you do a DELETE call on `${BASE_URL}/customer/`. Add the trailing slash.

https://github.com/prathameshkpai/userapi/blob/ba5a5ca69023470d499109987eb43d7b42be3a5b/index.js#L45

**Comment by prathameshkpai** [comment]
changed it
